# Generated by Django 5.1.4 on 2026-01-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('party_type', models.CharField(choices=[('TENANT', 'Арендатор'), ('OWNER', 'Собственник'), ('STAFF', 'Сотрудник')], default='TENANT', max_length=10, verbose_name='Тип')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО / Название')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечания')),
                ('custom_fields', models.JSONField(blank=True, default=dict, verbose_name='Доп. поля')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='Название/метка')),
                ('address', models.CharField(blank=True, default='', max_length=500, verbose_name='Адрес')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Свободен'), ('RENTED', 'В аренде'), ('SUSPENDED', 'Пауза'), ('ARCHIVED', 'Архив')], default='AVAILABLE', max_length=20, verbose_name='Статус')),
                ('custom_fields', models.JSONField(blank=True, default=dict, verbose_name='Доп. поля')),
            ],
            options={
                'verbose_name': 'Объект недвижимости',
                'verbose_name_plural': 'Объекты недвижимости',
            },
        ),
    ]
