# Generated by Django 5.1.4 on 2026-01-20 15:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('ACTIVE', 'Активен'), ('SUSPENDED', 'Приостановлен'), ('TERMINATING', 'Закрывается'), ('CLOSED', 'Закрыт'), ('CANCELLED', 'Отменен')], default='DRAFT', max_length=20, verbose_name='Статус договора')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ставка аренды (в месяц)')),
                ('due_day', models.PositiveSmallIntegerField(default=1, help_text='Лучше 1-28, чтобы не ломаться на феврале.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='День оплаты (1-28)')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Обеспечительный платеж (депозит)')),
                ('penalty_rule', models.JSONField(blank=True, default=dict, help_text='Пока просто JSON. Позже формализуем.', verbose_name='Правило пени (конфиг)')),
                ('custom_fields', models.JSONField(blank=True, default=dict, verbose_name='Доп. поля')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.property', verbose_name='Объект')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lease_contracts', to='core.party', verbose_name='Арендатор')),
            ],
            options={
                'verbose_name': 'Договор аренды',
                'verbose_name_plural': 'Договоры аренды',
            },
        ),
        migrations.CreateModel(
            name='PaymentObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('period_month', models.PositiveSmallIntegerField(verbose_name='Месяц')),
                ('due_date', models.DateField(verbose_name='Срок оплаты')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='К оплате')),
                ('status', models.CharField(choices=[('PLANNED', 'Запланировано'), ('DUE', 'Срок сегодня'), ('OVERDUE', 'Просрочено'), ('PAID_BY_TENANT', 'Оплачено арендатором'), ('CLOSED', 'Закрыто'), ('DISPUTED', 'Спор'), ('WRITTEN_OFF', 'Списано')], default='PLANNED', max_length=20, verbose_name='Статус')),
                ('penalty_rule_snapshot', models.JSONField(blank=True, default=dict, help_text='Фиксация правила на момент создания обязательства.', verbose_name='Снапшот правила пени')),
                ('custom_fields', models.JSONField(blank=True, default=dict, verbose_name='Доп. поля')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligations', to='core.leasecontract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Обязательство по оплате',
                'verbose_name_plural': 'Обязательства по оплате',
                'constraints': [models.UniqueConstraint(fields=('contract', 'period_year', 'period_month'), name='uniq_contract_period')],
            },
        ),
    ]
