# Generated by Django 5.1.4 on 2026-01-20 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_leasecontract_paymentobligation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leasecontract',
            name='responsible_user',
            field=models.ForeignKey(blank=True, help_text='Если не задан, будет использоваться ответственный по объекту.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный (по договору)'),
        ),
        migrations.AddField(
            model_name='paymentobligation',
            name='responsible_user',
            field=models.ForeignKey(blank=True, help_text='Фиксируется при создании обязательства.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obligations_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный (снапшот)'),
        ),
        migrations.AddField(
            model_name='property',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный (по объекту)'),
        ),
    ]
