# Generated by Django 5.1.4 on 2026-01-21 09:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_leasecontract_responsible_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время получения')),
                ('amount_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0 — если денег не получено, но факт зафиксирован', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Получено денег')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='core.paymentobligation', verbose_name='Обязательство')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кто зафиксировал')),
            ],
            options={
                'verbose_name': 'Факт получения денег',
                'verbose_name_plural': 'Факты получения денег',
            },
        ),
    ]
