# Generated by Django 5.1.4 on 2026-01-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paymentreceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentobligation',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Запланировано'), ('DUE', 'Срок сегодня'), ('OVERDUE', 'Просрочено'), ('PARTIAL', 'Частично оплачено'), ('PAID_BY_TENANT', 'Оплачено арендатором'), ('CLOSED', 'Закрыто'), ('DISPUTED', 'Спор'), ('WRITTEN_OFF', 'Списано')], default='PLANNED', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время фиксации'),
        ),
    ]
