# Generated by Django 5.1.4 on 2026-01-22 15:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_paymentobligation_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentreceipt',
            options={'ordering': ('-received_at',), 'verbose_name': 'Факт получения денег', 'verbose_name_plural': 'Факты получения денег'},
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата принятия бухгалтерией'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipts_accepted', to=settings.AUTH_USER_MODEL, verbose_name='Кто принял в бухгалтерии'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='accounting_status',
            field=models.CharField(choices=[('NOT_TRANSFERRED', 'Не передано в бухгалтерию'), ('TRANSFERRED', 'Передано в бухгалтерию'), ('ACCEPTED', 'Принято бухгалтерией')], db_index=True, default='NOT_TRANSFERRED', help_text='Внутренний статус: передано в бухгалтерию → принято бухгалтерией. Не влияет на факт оплаты арендатора.', max_length=20, verbose_name='Статус для бухгалтерии'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='transferred_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата передачи в бухгалтерию'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='transferred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipts_transferred', to=settings.AUTH_USER_MODEL, verbose_name='Кто передал в бухгалтерию'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0 — если денег не получено, но факт зафиксирован (например, звонок/обещание/ошибка).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Получено денег'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='received_by',
            field=models.ForeignKey(help_text='Пользователь, который внёс запись в систему. Может отличаться от того, кто фактически принял деньги.', on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipts_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто зафиксировал'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['accounting_status'], name='core_paymen_account_255372_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['received_at'], name='core_paymen_receive_83bbce_idx'),
        ),
    ]
